### ISSUE TITLE
doesn't compile on latest flixel (5.6.0)

### ISSUE THREAD

**Issue by Vortex2Oblivion** [FNF-CNE-Devs/hscript-improved#2]
```C:/HaxeToolkit/haxe/lib/hscript-improved/git/hscript/UsingHandler.hx:78: lines 78-80 : Type not found : flixel.graphics.frames.bmfont.BMFontBlockId```

**Comment by NeeEoo** [comment]
Will fix it when i get out of the hospital!

**Comment by Vortex2Oblivion** [comment]
Are you out of the hospital yet?

**Comment by NeeEoo** [comment]
Oh yea! I got home 2 days ago
